name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v6
      with:
        node-version: "22"
        cache: npm
        cache-dependency-path: extension/package-lock.json
    - name: Install dependencies
      run: npm ci
      working-directory: extension
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Cache Playwright
      uses: actions/cache@v6
      with:
        path: extension/node_modules
        key: ${{ runner.os }}-extension-${{ hashFiles('extension/package-lock.json') }}
    - name: Run Playwright tests
      run: npm --prefix ./extension run test:e2e
    - uses: actions/upload-artifact@v7
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: extension/playwright-report/
        retention-days: 30
